### ISSUE TITLE
Please, explain `safe html` better

### ISSUE THREAD

**Issue by robsonpeixoto** [scrapinghub/doc.scrapinghub.com#21]
>safe html
>Matches any HTML code which has no empty text content. Also performs some transformation and cleaning over the extracted data in order to safely show the correctly formatted HTML code on a web page.

What `transformation and cleaning` really do? Add some examples. Thanks.

**Comment by pablohoffman** [comment]
This is now explained in Portia's README: https://github.com/scrapinghub/portia#field-types
