### ISSUE TITLE
Improve command line client documentation

### ISSUE THREAD

**Issue by rdowinton** [scrapinghub/doc.scrapinghub.com#43]
The docs for the command line client are pretty bare. It's missing info on deploy options like --project, --list-targets etc. Maybe explain more about its relationship with scrapyd-deploy.

**Comment by pablohoffman** [comment]
`shub` command has a pretty decent help builtin, and the documentation suggests running `shub` alone to view it. I don't think we need to keep something separate (likely to get outdated) here.
