### ISSUE TITLE
Your java crawlera example doesn't work.

### ISSUE THREAD

**Issue by mlegris** [scrapinghub/doc.scrapinghub.com#80]
I copy pasted it. Used my API key. I get this output: 
Executing request GET /toronto HTTP/1.1 to http://yelp.ca:80 via http://paygo.crawlera.com:8010
----------------------------------------
HTTP/1.1 407 Proxy Authentication Required

I'm glad you took the time to test it out before offering it to us. Really helpful.

**Comment by mlegris** [comment]
I also tried this: 

```java

CredentialsProvider credsProvider = new BasicCredentialsProvider();
        credsProvider.setCredentials(
                new AuthScope("paygo.crawlera.com", 8010),
                new UsernamePasswordCredentials(apiKey, ""));
        CloseableHttpClient httpclient = HttpClients.custom()
                .setDefaultCredentialsProvider(credsProvider).build();

        String result = "";
        try {
            HttpHost target = new HttpHost("www.newcommerce.ca", 80, "http");
            HttpHost proxy = new HttpHost("paygo.crawlera.com", 8010);

            RequestConfig config = RequestConfig.custom()
                    .setProxy(proxy)
                    .build();
            HttpGet httpget = new HttpGet("/");
            httpget.addHeader("X-Crawlera-Use-HTTPS", "1");
            httpget.setConfig(config);

            System.out.println("Executing request " + httpget.getRequestLine() +
                    " to " + target + " via " + proxy);
            try {

                CloseableHttpResponse response = httpclient.execute(target, httpget);
                try {
                    System.out.println("----------------------------------------");
                    System.out.println(response.getStatusLine());
                    System.out.println("----------------------------------------");
                    result = EntityUtils.toString(response.getEntity());
                    System.out.println(result);
                } finally {
                    try {
                        response.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

            } catch(Exception e)
            {
                e.printStackTrace();
            }
        } finally {
            try {
                httpclient.close();
            } catch(IOException e)
            {
                e.printStackTrace();
            }
        }

        return result;
```

And it failed. I get Internal Server Error. My API KEY is correct. I quintuple checked it.

**Comment by qrilka** [comment]
@mlegris what version of Http Components do you use?
Could you give more details on that Internal Server Error you get?
Thanks

**Comment by mlegris** [comment]
httpclient-4.4.1.jar
httpcode-4.4.1.jar
commons-codec-1.10.jar

I'd love to give you more info on the 500 error, how do I do that? I tried the same requests using `curl` and it works fine.

Did someone really try this code and it worked? Sounds unreal right now haha :)

**Comment by mlegris** [comment]
I updated to 4.5, and your code now returns the same error as the code without the authCache (500 Internal Server Error).

**Comment by akarthik86** [comment]
@mlegris I just used the same code and it work fine for me. I got 407 when used httpclient-4.4.1 but when I replaced it with httpclient-4.5, I got the response. 
Can you just paste the enter output that you are getting whebn you execute the code ?  It would help us debug. 
Also just to double check, you are using this jar right - http://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5 ?

**Comment by akarthik86** [comment]
@mlegris @nestortoledo just found out that the website you are using - "www.newcommerce.ca" does not work with HTTPS. So, you would have to remove the below line in the code to make it work - 

httpget.addHeader("X-Crawlera-Use-HTTPS", "1");

Hope this helps.

**Comment by qrilka** [comment]
@mlegris the certificate of that website has expired in May of this year that's why you can't connect to HTTPS version of it with Crawlera.
The error message could be more informative of course though - our current handling of HTTPS problems is not quite perfect and we are working on improving Crawlera in that area.

**Comment by qrilka** [comment]
Please let us know if there is anything else we could do here or close the issue if there is nothing more to discuss

**Comment by mlegris** [comment]
Hi. So why is it that I specify this: 
`HttpHost target = new HttpHost("www.newcommerce.ca", 80, "http");` 

and then this: 
`httpget.addHeader("X-Crawlera-Use-HTTPS", "1");`

Which contradict each other really. The X-Crawlera-Use-HTTPS has precedence?

If I do this: 
`HttpHost target = new HttpHost("www.newcommerce.ca", 443, "https");` 
I still need to specify the X-Crawlera-Use-HTTPS header? Or one will suffice? thanks.

M

**Comment by mlegris** [comment]
ok I have some more specific help I need about yelp. I am trying to read : yelp.ca/toronto. What yelp does is it sets a cookie "location", containing something like: 
`{"city": "Toronto", "zip": "", "address1": "", "address2": "", "address3": "", "state": "ON", "country": "CA", "unformatted": "Toronto, ON"}` 

And then forwards 303 to http://www.yelp.ca

However when I run the request through Crawlera (using the code above) that now works, and having configured CloseableHttpClient to use a cookie store, I get the Atlanta, or Seattle, or .. wherever page.

Also, if I set the cookie in the request manually, it doesn't seem to get passed through.

So my question is: is crawlera handling the forward command on it's side, or is HttpClient on my side actually handling it? And if so, assuming the cookies do get set, why am I getting the wrong page back?

Is there a way to diagnose a particular request to know what happens really on your side? 

thanks a lot

M

**Comment by mlegris** [comment]
In case you want to try it yourself: 
````java
        CredentialsProvider credsProvider = new BasicCredentialsProvider();
        credsProvider.setCredentials(
                new AuthScope("paygo.crawlera.com", 8010),
                new UsernamePasswordCredentials(apiKey, ""));

        CookieStore cookieStore = new BasicCookieStore();
        BasicClientCookie cookie = new BasicClientCookie("location", "{\"city\": \"Toronto\", \"zip\": \"\", \"address1\": \"\", \"address2\": \"\", \"address3\": \"\", \"state\": \"ON\", \"country\": \"CA\", \"unformatted\": \"Toronto, ON\"}");
        cookie.setPath("/");
        cookie.setDomain("yelp.ca");
        cookieStore.addCookie(cookie);

        CloseableHttpClient httpclient = HttpClients.custom()
                .setDefaultCookieStore(cookieStore)
                .setDefaultCredentialsProvider(credsProvider).build();

        String result = "";
        try {
            HttpHost target = new HttpHost("www.yelp.ca", 80, "http");
            HttpHost proxy = new HttpHost("paygo.crawlera.com", 8010);

            AuthCache authCache = new BasicAuthCache();
            BasicScheme basicAuth = new BasicScheme();

            try {
                basicAuth.processChallenge(
                        new BasicHeader(HttpHeaders.PROXY_AUTHENTICATE,
                                "Basic realm=\"Crawlera\""));
            } catch(MalformedChallengeException e)
            {
                e.printStackTrace();
            }

            authCache.put(proxy, basicAuth);

            HttpClientContext ctx = HttpClientContext.create();
            ctx.setAuthCache(authCache);

            RequestConfig config = RequestConfig.custom()
                    .setProxy(proxy)
                    .build();
            HttpGet httpget = new HttpGet("/");

            // httpget.addHeader("X-Crawlera-Use-HTTPS", "1");
            httpget.setConfig(config);

            System.out.println("Executing request " + httpget.getRequestLine() +
                    " to " + target + " via " + proxy);
            try {

                CloseableHttpResponse response = httpclient.execute(target, httpget, ctx);
                try {
                    System.out.println("----------------------------------------");
                    System.out.println(response.getStatusLine());
                    System.out.println("----------------------------------------");
                    result = EntityUtils.toString(response.getEntity());
                    System.out.println(result);
                } finally {
                    try {
                        response.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

            } catch(Exception e)
            {
                e.printStackTrace();
            }
        } finally {
            try {
                httpclient.close();
            } catch(IOException e)
            {
                e.printStackTrace();
            }
        }

        return result;
````

**Comment by qrilka** [comment]
@mlegris normally we handle such questions through help@scrapinghub.com but if you ask here are some comments to your questions:

1. `HttpHost` and `X-Crawlera-Use-HTTPS` have nothing in common, the first one is a part of Http Components and have nothing to do with Crawlera and the second one is described at http://doc.scrapinghub.com/crawlera.html#x-crawlera-use-https and mostly used to pass to HTTP proxy without using `CONNECT` method of HTTP

2. In our logs I see you do requests like `http://www.yelp.ca:80/toronto` which get redirected to `http://www.yelp.ca/`, I suppose yelp does not like a port in your URL

3. Crawlera by default uses per proxy cookie persistence which could sometime get in the way of your spider but you could disable it with http://doc.scrapinghub.com/crawlera.html#x-crawlera-cookies

I'm closing this issue as Crawlera support is done through help@scrapinghub.com and invite you to post any further questions there.

Thanks
